export type UserRole = "staff" | "admin" | "superuser";

export type Permission =
  // Catalog
  | "inventory.catalog.add"
  | "inventory.catalog.read"
  | "inventory.catalog.read_own"
  | "inventory.catalog.change"
  | "inventory.catalog.change_own"
  | "inventory.catalog.delete"
  | "inventory.catalog.manage"
  | "inventory.catalog.manage_own"
  | "inventory.catalog.refund"
  // Warehouses
  | "inventory.warehouses.add"
  | "inventory.warehouses.read"
  | "inventory.warehouses.read_own"
  | "inventory.warehouses.change"
  | "inventory.warehouses.change_own"
  | "inventory.warehouses.delete"
  | "inventory.warehouses.manage"
  | "inventory.warehouses.manage_own"
  | "inventory.warehouses.refund"
  // Adjustments
  | "inventory.adjustments.add"
  | "inventory.adjustments.read"
  | "inventory.adjustments.read_own"
  | "inventory.adjustments.change"
  | "inventory.adjustments.change_own"
  | "inventory.adjustments.delete"
  | "inventory.adjustments.manage"
  | "inventory.adjustments.manage_own"
  | "inventory.adjustments.refund"
  // Stock
  | "inventory.stock.add"
  | "inventory.stock.read"
  | "inventory.stock.read_own"
  | "inventory.stock.change"
  | "inventory.stock.change_own"
  | "inventory.stock.delete"
  | "inventory.stock.manage"
  | "inventory.stock.manage_own"
  | "inventory.stock.refund"
  // Transfers
  | "inventory.transfers.add"
  | "inventory.transfers.read"
  | "inventory.transfers.read_own"
  | "inventory.transfers.change"
  | "inventory.transfers.change_own"
  | "inventory.transfers.delete"
  | "inventory.transfers.manage"
  | "inventory.transfers.manage_own"
  | "inventory.transfers.refund"
  // Suppliers
  | "inventory.suppliers.add"
  | "inventory.suppliers.read"
  | "inventory.suppliers.read_own"
  | "inventory.suppliers.change"
  | "inventory.suppliers.change_own"
  | "inventory.suppliers.delete"
  | "inventory.suppliers.manage"
  | "inventory.suppliers.manage_own"
  | "inventory.suppliers.refund"
  // Purchase orders
  | "inventory.purchases.add"
  | "inventory.purchases.read"
  | "inventory.purchases.read_own"
  | "inventory.purchases.change"
  | "inventory.purchases.change_own"
  | "inventory.purchases.delete"
  | "inventory.purchases.manage"
  | "inventory.purchases.manage_own"
  | "inventory.purchases.refund"
  // Approvals (approval matrix)
  | "inventory.approvals.view"
  | "inventory.approvals.add"
  | "inventory.approvals.change"
  | "inventory.approvals.delete"
  | "inventory.approvals.manage"
  // Reports
  | "inventory.reports.add"
  | "inventory.reports.read"
  | "inventory.reports.read_own"
  | "inventory.reports.change"
  | "inventory.reports.change_own"
  | "inventory.reports.delete"
  | "inventory.reports.manage"
  | "inventory.reports.manage_own"
  | "inventory.reports.refund"
  // Settings
  | "inventory.settings.add"
  | "inventory.settings.read"
  | "inventory.settings.read_own"
  | "inventory.settings.change"
  | "inventory.settings.change_own"
  | "inventory.settings.delete"
  | "inventory.settings.manage"
  | "inventory.settings.manage_own"
  | "inventory.settings.refund"
  // Platform
  | "inventory.platform.add"
  | "inventory.platform.read"
  | "inventory.platform.read_own"
  | "inventory.platform.change"
  | "inventory.platform.change_own"
  | "inventory.platform.delete"
  | "inventory.platform.manage"
  | "inventory.platform.manage_own"
  | "inventory.platform.refund"
  // Notifications
  | "inventory.notifications.add"
  | "inventory.notifications.read"
  | "inventory.notifications.read_own"
  | "inventory.notifications.change"
  | "inventory.notifications.change_own"
  | "inventory.notifications.delete"
  | "inventory.notifications.manage"
  | "inventory.notifications.manage_own"
  | "inventory.notifications.refund"
  // Config
  | "inventory.config.view"
  | "inventory.config.manage"
  // Users
  | "inventory.users.manage"
  // Audit + stock counts
  | "inventory.audit.view"
  | "inventory.stock_count.view"
  | "inventory.stock_count.add"
  | "inventory.stock_count.change"
  | "inventory.stock_count.approve";

export interface UserProfile {
  id: string;
  email: string;
  fullName: string;
  roles: UserRole[];
  permissions: Permission[];
  organizationId: string;
  tenantId: string;
  tenantSlug: string;
  isPlatformOwner?: boolean;
  isSuperUser?: boolean;
}
